### ISSUE TITLE
Could not pass InteractInventoryEvent$Close$Impl to Plugin{

### ISSUE THREAD

**Issue by ProsperCraft** [Akkyen/LootChest#1]
https://gist.github.com/ProsperCraft/ea195fa58fd805adf00248f5dca703e7

I get this several times a second.

    Minecraft: 1.10.2
    SpongeAPI: 5.1.0-SNAPSHOT-7869dae
    SpongeForge: 1.10.2-2123-5.1.0-BETA-1879

**Comment by FiveEYZ** [comment]
found that this happen only when u close a inventory from a mod like a machine from IC2, EnderIO or any mod that have a GUI.

Tested a Controller from Refined Storage(it's a GUI with no inventory) and i got this:
https://gist.github.com/FiveEYZ/4d728be9e49d40aeb9f2e24d5be81e5d

In ProsperCraft's gist that error happen when the player closed the GUI from a Sagmill from EnderIO.

vanilla stuff works 100%

**Comment by Akkyen** [comment]
I will add a check to ensure that I have a standart MC Chest.

**Comment by Akkyen** [comment]
Just now I added some code that should ensure that my plugin nolonger tries to cast Invs of ModChests to Invs of the default Chest

**Comment by Akkyen** [comment]
Update 7b7c015 should fix it

**Comment by Akkyen** [comment]
Got fixxed with Update 7b7c015
or called Update 0.9.1.2
