### ISSUE TITLE
Could not pass InteractBlockEvent$Primary$MainHand$Impl

### ISSUE THREAD

**Issue by FiveEYZ** [Akkyen/LootChest#2]
Thanks for a great plugin!

but unfortunately im getting this error
https://gist.github.com/FiveEYZ/7a9a503bd2ee6b4541689dc989858313

**Comment by Akkyen** [comment]
Forgot to check if Optional has an value.

Got fixxed in Commit:
24e9c80bf63a458248480c536521abe66ad4c307
